POST http://localhost:5000/api/v1/auth/signin
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWNlZTA5ZTY2MzcxMjhiZjgwNTI4MCIsImFkbWluIjp0cnVlLCJpYXQiOjE3MzAwOTc2MDIsImV4cCI6MTczMDE4NDAwMn0.NsvvMiJoB-MFJwG-XX05EPNkvQt5tSpEt2tZ5_fSrHU

# {
#     "query": "f.patchelli17"
# }

    # "fullname": "jhonad radii" ,
# {
#     "email": "f.patchelli@gmail.com" ,
#     "password": "Stella123"
# }

# {
#     "username": "f.patchelli"
# }

# {
#     "title":"Test event",
#       "banner":"blob:http://localhost:3000/947cb5eb-e3be-47d2-9dec-d65ba6cc0ef0",
#       "category":"",
#       "content":[],
#       "description":"Short des description",
#       "endDateTime":"Wed Oct 30 2024 10:00:00 GMT+0100 (West Africa Standard Time) {}",
#       "isFree":true,
#       "location":"Entre nous bar",
#       "price":0,
#       "startDateTime":"Tue Oct 29 2024 08:30:00 GMT+0100 (West Africa Standard Time) {}",
#       "tags":["tags", "showcase"],
#       "author":"",
#       "url":""
# }

# {
#     "fullname":"Jhonny Patson" ,
#     "email": "jhon@gmail.com" ,
#     "password": "Joh2n4123"
# }

# {
#     "fullname":"Malick" ,
#     "email": "malickson@gmail.com" ,
#     "password": "Malick1234@",
#     "role": "admin"
# }

{
    "email": "francois@gmail.com" ,
    "password": "Francois1234"
}
    # "fullname":"Francois Oyabi" ,
    # "role": ""

# {
#     "fullname":"Mohamed Jewiti" ,
#     "email": "mohamedj@gmail.com" ,
#     "password": "Mohamed1234",
#     "role": "moderator"
# }
